### ISSUE TITLE
Opt-Out: Ne pas être contacté par les sponsors

### ISSUE THREAD

**Issue by ericlemerdy** [agile-france/site-2011#1]
Dans l'inscription d'un utilisateur et dans la gestion du compte personnel, il devrait y avoir un champ activé par défaut: "Je ne souhaite pas être contacté par les sponsors de la conférence."

**Comment by thenrio** [comment]
implemented in /account : optin, default unchecked
"J'autorise les sponsors de la conférence à me contacter"

available in v0.1.0

**Comment by thenrio** [comment]
optins added to registration

**Comment by ericlemerdy** [comment]
very good !
