### ISSUE TITLE
Add a contact page

### ISSUE THREAD

**Issue by ericlemerdy** [agile-france/site-2011#12]
A new page should be added with the contact e-mail and the staff team (with gravatars, and names)

**Comment by thenrio** [comment]
Yep and where is the github voice ? It is on http://charming-conference.heroku.com/ but not in production site ?

**Comment by ericlemerdy** [comment]
Since it broked up header layout, I never reported back this heroku commit in the github repo... lazy I am.

Envoyé depuis mon HTC Desire d'Orange

----- Reply message -----
De : "thierryhenrio" reply@reply.github.com
Date : jeu., mai 5, 2011 15:38
Objet : [GitHub] Add a contact page [agile-france/conference-app GH-12]
Pour : eric.lemerdy@laposte.net

Yep and where is the github voice ? It is on http://charming-conference.heroku.com/ but not in production site ?

## 

Reply to this email directly or view it on GitHub:
https://github.com/agile-france/conference-app/issues/12#comment_1105636
