### ISSUE TITLE
La page d'accueil devrait diriger vers la prochaine conférence (AF2011)

### ISSUE THREAD

**Issue by ericlemerdy** [agile-france/site-2011#2]
Aujourd'hui, on tombe sur la liste des conférences.
L'utilisateur doit cliquer une fois sur 'Agile France 2011' pour pouvoir entrer dans la conférence.
Il faudrait que ça redirige directement vers la conférence la plus récente.

**Comment by thenrio** [comment]
is on v0.3.0
